# Generated by Django 3.2.6 on 2021-09-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=100, null='no_status'),
            preserve_default='no_status',
        ),
    ]
